AgricultureManagementSystem/AgricultureManagementSystem/Controllers/FishController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AgricultureManagementSystem.Helper;
using AgricultureManagementSystem.Models;

namespace AgricultureManagementSystem.Controllers
{
    [SessionExpire]
    public class FishController : Controller
    {
        private AMSEntities db = new AMSEntities();

        // GET: Fish
        public ActionResult Index()
        {
            var fishes = db.Fishes.Include(f => f.FishType);
            return View(fishes.ToList());
        }

        // GET: Fish/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fish fish = db.Fishes.Find(id);
            if (fish == null)
            {
                return HttpNotFound();
            }
            return View(fish);
        }

        // GET: Fish/Create
        public ActionResult Create()
        {
            ViewBag.FishTypeId = new SelectList(db.FishTypes, "Id", "Name");
            return View();
        }

        // POST: Fish/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Date,FishTypeId,Quantity")] Fish fish)
        {
            if (ModelState.IsValid)
            {
                db.Fishes.Add(fish);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FishTypeId = new SelectList(db.FishTypes, "Id", "Name", fish.FishTypeId);
            return View(fish);
        }

        // GET: Fish/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fish fish = db.Fishes.Find(id);
            if (fish == null)
            {
                return HttpNotFound();
            }
            ViewBag.FishTypeId = new SelectList(db.FishTypes, "Id", "Name", fish.FishTypeId);
            return View(fish);
        }

        // POST: Fish/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Date,FishTypeId,Quantity")] Fish fish)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fish).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FishTypeId = new SelectList(db.FishTypes, "Id", "Name", fish.FishTypeId);
            return View(fish);
        }

        // GET: Fish/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fish fish = db.Fishes.Find(id);
            if (fish == null)
            {
                return HttpNotFound();
            }
            return View(fish);
        }

        // POST: Fish/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Fish fish = db.Fishes.Find(id);
            db.Fishes.Remove(fish);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgricultureManagementSystem/AgricultureManagementSystem/Controllers/SeedsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AgricultureManagementSystem.Helper;
using AgricultureManagementSystem.Models;

namespace AgricultureManagementSystem.Controllers
{
    [SessionExpire]
    public class SeedsController : Controller
    {
        private AMSEntities db = new AMSEntities();

        // GET: Seeds
        public ActionResult Index()
        {
            var seeds = db.Seeds.Include(s => s.SeedType);
            return View(seeds.ToList());
        }

        // GET: Seeds/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seed seed = db.Seeds.Find(id);
            if (seed == null)
            {
                return HttpNotFound();
            }
            return View(seed);
        }

        // GET: Seeds/Create
        public ActionResult Create()
        {
            ViewBag.SeedTypeId = new SelectList(db.SeedTypes, "Id", "Name");
            return View();
        }

        // POST: Seeds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Date,SeedTypeId,Quantity")] Seed seed)
        {
            if (ModelState.IsValid)
            {
                db.Seeds.Add(seed);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SeedTypeId = new SelectList(db.SeedTypes, "Id", "Name", seed.SeedTypeId);
            return View(seed);
        }

        // GET: Seeds/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seed seed = db.Seeds.Find(id);
            if (seed == null)
            {
                return HttpNotFound();
            }
            ViewBag.SeedTypeId = new SelectList(db.SeedTypes, "Id", "Name", seed.SeedTypeId);
            return View(seed);
        }

        // POST: Seeds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Date,SeedTypeId,Quantity")] Seed seed)
        {
            if (ModelState.IsValid)
            {
                db.Entry(seed).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SeedTypeId = new SelectList(db.SeedTypes, "Id", "Name", seed.SeedTypeId);
            return View(seed);
        }

        // GET: Seeds/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seed seed = db.Seeds.Find(id);
            if (seed == null)
            {
                return HttpNotFound();
            }
            return View(seed);
        }

        // POST: Seeds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Seed seed = db.Seeds.Find(id);
            db.Seeds.Remove(seed);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgricultureManagementSystem/AgricultureManagementSystem/Views/Shared/_CommonLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    <link rel="icon" type="image/png" href="~/Content/images/logo.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="@Url.Action("Index","Home")"> Agriculture & Farmer </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index","Home")">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("About","Home")">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Contact","Home")">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Login","Home")">Login</a>
                </li>
                @*<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown link
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>*@
            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        @RenderBody()
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

AgricultureManagementSystem/AgricultureManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AGRICULTURE </title>
    <link rel="icon" type="image/png" href="~/Content/images/logo.png" />
    <!-- Bootstrap -->
    <link href="~/Content/theme/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/Content/theme/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/Content/theme/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="~/Content/theme/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

    <!-- Datatables -->
    <link href="~/Content/theme/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/theme/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/theme/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/theme/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/theme/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

    @*Jquery UI*@
    <link rel="stylesheet" type="text/css" href="~/Content/jqueryUi/jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/jqueryUi/jquery-ui.structure.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/jqueryUi/jquery-ui.theme.css" />

    <!-- Custom Theme Style -->
    <link href="~/Content/theme/build/css/custom.min.css" rel="stylesheet">
    <style>
        .glow {
            font-size: 14px;
            color: #fff;
            text-align: left;
            -webkit-animation: glow 1s ease-in-out infinite alternate;
            -moz-animation: glow 1s ease-in-out infinite alternate;
            animation: glow 1s ease-in-out infinite alternate;
        }

        @@-webkit-keyframes glow {
            from {
                text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #e60073, 0 0 40px #e60073, 0 0 50px #e60073, 0 0 60px #e60073, 0 0 70px #e60073;
            }

            to {
                text-shadow: 0 0 20px #fff, 0 0 30px #ff4da6, 0 0 40px #ff4da6, 0 0 50px #ff4da6, 0 0 60px #ff4da6, 0 0 70px #ff4da6, 0 0 80px #ff4da6;
            }
        }
    </style>
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="@Url.Action("Dashboard","Home")" class="site_title">@*<i class="fa fa-paw"></i>*@ <span>AGRICULTURE</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <img src="~/Content/images/logo.png" class="img-circle profile_img" />
                        </div>
                        <div class="profile_info glow">
                            <span>Welcome to</span>
                            <h2>AGRICULTURE</h2>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <!-- /menu profile quick info -->
                    <br />
                    <div style="display: none;" class="overlay" id="loader">
                        <i class="fa fa-refresh fa-spin"></i>
                    </div>
                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <ul class="nav side-menu">
                                <li>
                                    <a href="@Url.Action("Dashboard","Home")">
                                        <i class="fa fa-home"></i>
                                        Home
                                    </a>
                                </li>
                                <li>
                                    <a><i class="fa fa-edit"></i> Basic <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("Index","Farmers")">Farmers</a></li>

                                        <li><a href="@Url.Action("Index", "FishTypes")">Fish Types</a></li>
                                        <li><a href="@Url.Action("Index", "SeedTypes")">Seed Types</a></li>

                                        <li><a href="@Url.Action("Index", "Fish")">Fish</a></li>
                                        <li><a href="@Url.Action("Index", "Seeds")">Seeds</a></li>
                                        <li><a href="@Url.Action("Index", "Fertilizers")">Fertilizers</a></li>
                                        

                                        <li><a href="@Url.Action("Index", "ReceiveOfProducts")">Receive Of Products</a></li>
                                        <li><a href="@Url.Action("Index", "SaplingSeeds")">Sapling Seeds</a></li>
                                        <li><a href="@Url.Action("Index", "DistributionOfSeeds")">Distribution Of Seeds</a></li>
                                        <li><a href="@Url.Action("Index", "DistributionOfFish")">Distribution Of Fish</a></li>

                                        @*<li><a href="@Url.Action("Index", "FishProjects")">Fish Projects</a></li>
        <li><a href="@Url.Action("Index", "RiceSeeds")">Rice Seeds</a></li>

        <li><a href="@Url.Action("Index","VegetableSeeds")">Vegetable Seeds</a></li>*@
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-cogs"></i> System <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("Index", "UserAccounts")">User Account</a></li>
                                    </ul>
                                </li>

                            </ul>
                        </div>

                    </div>
                    <!-- /sidebar menu -->
                </div>
            </div>
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <img src="images/img.jpg" alt="">
                                    @if (Session["username"] != null)
                                    {
                                        <span>@Session["username"].ToString()</span>
                                    }
                                    <span class=" fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                </ul>
                            </li>

                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    <div class="clearfix"></div>
                    @if (TempData["ErrorMessage"] != null)
                    {
                        <div class="alert alert-danger" role="alert">
                            @TempData["ErrorMessage"]
                        </div>
                    }
                    @if (TempData["SuccessMessage"] != null)
                    {
                        <div class="alert alert-success" role="alert">
                            @TempData["SuccessMessage"]
                        </div>
                    }
                    @RenderBody()
                </div>
            </div>
            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    Inventory management system by <a target="_blank" href="https://www.fiverr.com/share/382WA9">Tofail Alam Tushar</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>
    <!-- jQuery -->
    <script src="~/Content/theme/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/theme/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="~/Content/theme/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/Content/theme/vendors/nprogress/nprogress.js"></script>

    <!-- iCheck -->
    <script src="~/Content/theme/vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="~/Content/theme/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/theme/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/theme/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/Content/theme/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="~/Content/theme/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="~/Content/theme/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Content/theme/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/Content/theme/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="~/Content/theme/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="~/Content/theme/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Content/theme/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="~/Content/theme/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="~/Content/theme/vendors/jszip/dist/jszip.min.js"></script>
    <script src="~/Content/theme/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="~/Content/theme/vendors/pdfmake/build/vfs_fonts.js"></script>


    @*Jquery UI*@
    <script type="text/javascript" src="~/Scripts/jqueryUi/jquery-ui.js"></script>

    @*Jquery Multiselect*@
    <script type="text/javascript" src="~/Scripts/jqueryUi/jquery.multiselect.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jqueryUi/jquery.multiselect.filter.min.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="~/Content/theme/build/js/custom.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>